name: Release Web Component

on:
  workflow_dispatch:

jobs:
  publish-react:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish
        working-directory: ./libraries/react
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm ci
          npm run build
          cd dist
          npm publish
